#OUTPUT
print("############################################################################")
print("# PRODUCTO DEL TOTAL ACTIVO CON EL TOTAL PASIVO AÑO 2007 #")
print("#####################################################################")
print("# total activo 2007: ", total_activo_2007,"     #")
print("# total pasivo 2007: ", total_pasivo_2007,"      #")
print("#####################################################################")
print("# total: ", total,"    #")
print("# buena suma: ", buena_suma,"     #")
print("#####################################################################")
