#OUTPUT
print("############################################################################")
print("# PRODUCTO DEL TOTAL ACTIVO CON EL TOTAL PASIVO AÑO 2006 #")
print("#####################################################################")
print("# total activo 2008: ", total_activo_2006,"     #")
print("# total pasivo 2008: ", total_pasivo_2006,"    #")
print("#####################################################################")
print("# total: ", total,"    #")
print("# buena suma: ", buena_suma,"     #")
print("#####################################################################")
