#OUTPUT
print("############################################################################")
print("# SUMA DE LAS VENTAS NETAS DEL AÑO 2007 Y 2008 #")
print("#####################################################################")
print("# ventas netas 2007: ",ventas_netas_2007,"   #"  )
print("# ventas netas 2008: ",ventas_netas_2008,"   #")
print("###########################################")
print("# total:s/. ",total,"      #")
print("# mala venta neta: ",mala_venta_neta,"      #")
print("#####################################################################")
