#OUTPUT
print("############################################################################")
print("# PRODUCTO DEL TOTAL ACTIVO CON EL TOTAL PASIVO AÑO 2008 #")
print("#####################################################################")
print("# total activo 2008: ", total_activo_2008,"     #")
print("# total pasivo 2008: ", total_pasivo_2008,"    #")
print("#####################################################################")
print("# total: ", total,"    #")
print("# buena suma: ", buena_suma,"     #")
print("#####################################################################")
