#OUTPUT
print("############################################################################")
print("# INCREMENTO DE LA UTILIDAD BRUTA DEL AÑO 2005 Y 2006 #")
print("#####################################################################")
print("# utilidad bruta 2005: ", utilidad_bruta_2005,"    # ")
print("# utilidad bruta 2006: ", utilidad_bruta_2006,"     #")
print("#####################################################################")
print("# total: s/. ", total,"       #")
print("# buena_utildad: ", buena_utildad,"       #")
print("#####################################################################")
