#OUTPUT
print("#########################")
print("#   TOTAL DE LIBROS VENDIDOS   #")
print("#########################")
print("# libro de auditoria tributaria: ",libro_de_auditoria_tributaria,"   #"  )
print("# libro manual del contador: ",libro_manual_del_contador,"   #")
print("# compendio laboral: ",compendio_laboral,"   #")
print("###########################################")
print("# total:s/. ",total,"      #")
print("# mala venta: ",mala_venta,"      #")
print("#####################################################################")
