#OUTPUT
print("##########################################################")
print("# SUMA DE LOS QUE USAN CHROME Y FIREFOX EN OCEANIA  #")
print("#####################################################################")
print("# chrome: ", chrome,"       #")
print("# firefox: ", firefox,"       #"     )
print("#####################################################################")
print("# total: % ",total,"      #")
print("# mas usados:  ",mas_usados,"      #")
print("#####################################################################")
